.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd June 14, 2009
.Os "Mac OS X"
.Dt APP \&1 "CLIMac Reference Manual"
.Sh NAME                 \" Section Header - required - don't modify 
.Nm app
.Nd find OS X applications
.Sh SYNOPSIS             \" Section Header - required - don't modify
.\".Nm
.\".Ar app-name
.\".Nm
.\".Op Fl l
.\".Op Fl a \*(Ba Fl u Ar URL-scheme \*(Ba Fl t Ar UTI
.\".Nm
.\".Op Fl b Ar bundleID \*(Ba Fl w Ar windowID \*(Ba Fl f Ar file
.Nm
.Ar name
.Nm
.Op Fl l
.Op Fl a
.Nm
.Op Fl l
.Op Fl b \*(Ba f \*(Ba w \*(Ba u \*(Ba t
.Ar argument
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Pp
The
.Nm
utility prints the path at which application(s) are located. In the absence of any other flags or options, the single argument is interpreted as the name of an application, and the full path to its bundle is printed.
.Sh OPTIONS
.Pp
In each case, the absolute paths to the applications matching the criteria are printed. Applications are specified by:
.Bl -ohang
.It Fl l Ns / Ns Fl -all
.D1 All applications .
.It Fl a Ns / Ns Fl -active
.D1 The currently active Po frontmost Pc application .
.D1 With the Fl l No flag , all launched applications .
.It Fl u Ns / Ns Fl -scheme Aq Ar url-scheme
.D1 Application that opens URLs with the specified scheme .
.D1 With the Fl l No flag , all applications able to handle the specified URL scheme .
.It Fl t Ns / Ns Fl -type Aq Ar UTI
.D1 Application that opens files of the specified content-type Po Uniform Type Identifier Pc .
.D1 With the Fl l No flag , all applications able to open files of the specified content-type .
.Pp
.D1 Use Xr uti 1 to determine UTIs .
.It Fl b Ns / Ns Fl -bundle Aq Ar bundle-ID
.D1 Application that has the specified identifier . Pq The bundle ID is a unique identifier for an application that is defined in the Info.plist under the key Sq CFBundleIdentifier
.It Fl f Ns / Ns Fl -file Aq Ar file
.D1 Application that will open the specified file . I\&t is recommeded to use the Fl t No option in the general case , and the Fl f No option only when information about a specific file is needed .
.It Fl w Ns / Ns Fl -window Aq Ar window-ID
.D1 Application that owns the specified window .
.Pp
.D1 Use Xr wid 1 to determine window IDs .
.El
.Pp
Only the default application for the given criteria is printed unless the
.Fl l
flag is also given.
.\".Sh FILES                \" File used or created by the topic of the man page
.Sh EXAMPLES
.Bd -literal -offset indent
% app iTunes
/Applications/iTunes.app

% app -a
/Applications/Utilities/Terminal.app

% app -u https
/Applications/Safari.app

% app -l -u https
/Applications/Chromium.app
/Applications/Firefox.app
/Applications/Safari.app

% app -t public.tiff
/Applications/Preview.app

% app -f .zshrc
/Applications/TextEdit.app

% app -f /bin/ls
/Applications/Utilities/Terminal.app

% app -b com.apple.Dock
/System/Library/CoreServices/Dock.app
.Ed
.Sh DIAGNOSTICS
The
.Nm
utility exits 0 on success, and \*(Gt0 if an error occurs.
.\".Sh COMPATIBILITY
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr setapp 1 ,
.Xr open 1 ,
.Xr uti 1 ,
.Xr win 1
.\" .Sh BUGS              \" Document known, unremedied bugs
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner
.Sh AUTHORS
.Pp
The
.Nm
utility was written by
.An Sq Vacuous Virtuoso
.Aq http://lipidity.com