.Dd June 14, 2009
.Os "Mac OS X"
.Dt PDFCAT \&1 "CLIMac Reference Manual"
.Sh NAME                 \" Section Header - required - don't modify 
.Nm pdfcat
.Nd concatenate PDF files
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Ar
.Op Fl o Ar output.pdf
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Pp
The
.Nm
utility reads PDF files sequentially and combines all their pages into one document.
.\".Sh FILES                \" File used or created by the topic of the man page
.\".Sh EXAMPLES
.Sh DIAGNOSTICS
The
.Nm
utility exits 0 on success, and \*(Gt0 if an error occurs.
.\".Sh COMPATIBILITY
.\".Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.\".Xr cp 1 ,
.\".Xr mv 1
.\" .Sh BUGS              \" Document known, unremedied bugs
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner
.Sh AUTHORS
.Pp
The
.Nm
utility was written by
.An Sq Vacuous Virtuoso
.Aq http://lipidity.com