.Dd June 14, 2009
.Os "Mac OS X"
.Dt .UTILITY \&1 "CLIMac Reference Manual"
.Sh NAME
.Nm .UTILITY
.Nd doCrazyThings
.Sh SYNOPSIS
.Nm
.Ar
.Sh DESCRIPTION
.Pp
The
.Nm
utility does crazy things.
.\" .Sh IMPLEMENTATION NOTES
.\".Sh FILES                \" File used or created by the topic of the man page
.\".Sh EXAMPLES
.Sh DIAGNOSTICS
The
.Nm
utility exits 0 on success, and \*(Gt0 if an error occurs.
.\".Sh COMPATIBILITY
.\".Sh SEE ALSO 
.\".Xr cp 1 ,
.\".Xr mv 1
.\" .Sh HISTORY
.Sh AUTHORS
.Pp
The
.Nm
utility was written by
.An Sq Vacuous Virtuoso
.Aq http://lipidity.com
.\" .Sh BUGS