.Dd June 14, 2009
.Os "Mac OS X"
.Dt PDFINFO \&1 "CLIMac Reference Manual"
.Sh NAME
.Nm pdfinfo
.Nd list PDF document attributes
.Sh SYNOPSIS
.Nm
.Ar file
.Sh DESCRIPTION
.Pp
The
.Nm
utility prints the number of pages in the specified PDF document, as well as any attributes that may be present.
.\" .Sh IMPLEMENTATION NOTES
.\".Sh FILES                \" File used or created by the topic of the man page
.\".Sh EXAMPLES
.Sh DIAGNOSTICS
The
.Nm
utility exits 0 on success, and \*(Gt0 if an error occurs.
.\".Sh COMPATIBILITY
.\".Sh SEE ALSO 
.\".Xr cp 1 ,
.\".Xr mv 1
.\" .Sh HISTORY
.Sh AUTHORS
.Pp
The
.Nm
utility was written by
.An Sq Vacuous Virtuoso
.Aq http://lipidity.com
.\" .Sh BUGS